// <auto-generated/>
// Source: lib.rs
// Generated by RustMaui.Generators — do not edit.
// To override a binding declare it in Rust.cs — it will be skipped here.

using System.Runtime.InteropServices;

namespace UseSkiaSharp;

public static partial class Rust
{
    /// <summary>
    /// Native library name inferred from rust/Cargo.toml [package].name or the RustLibName MSBuild override.
    /// </summary>
    private const string Lib = "useskiasharp_native";

    [LibraryImport(Lib, EntryPoint = "add")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int Add(int a, int b);

}
