// <auto-generated/>
// Source: lib.rs
// Generated by RustMaui.Generators — do not edit.
// To override a binding declare it in Rust.cs — it will be skipped here.

using System.Runtime.InteropServices;

namespace UseSkiaSharp;

public static partial class Rust
{
    /// <summary>
    /// Native library name inferred from rust/Cargo.toml [package].name or the RustLibName MSBuild override.
    /// </summary>
    private const string Lib = "useskiasharp_native";

    [LibraryImport(Lib, EntryPoint = "draw_circle")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int DrawCircle(IntPtr canvas, float cx, float cy, float radius, uint colorArgb);

    [LibraryImport(Lib, EntryPoint = "last_error_message")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial nuint LastErrorMessage(IntPtr buffer, nuint bufferLen);

}
